export const SHOES_ACTION_TYPES = {
    FETCH_SHOES_CATEGORIES_START: 'FETCH_SHOES_CATEGORIES_START',
    FETCH_SHOES_CATEGORIES_SUCCESS: 'FETCH_SHOES_CATEGORIES_SUCCESS',
    FETCH_SHOES_CATEGORIES_FAILED: 'FETCH_SHOES_CATEGORIES_FAILED'
}